apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: opentelemetry

resources:
- rbac.yml
- cluster-collector.yml
- gateway-collector.yml
- daemonset-collector.yml
- gateway-neg.yml
- honeycomb-secrets.yml